skin:
  path: ${user.home}/xjskin/

server:
  servlet:
    session:
      # Session 过期时间
      timeout: 12h
  # 服务器监听的端口
  port: 7373

spring:
  # 数据库连接信息
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    hikari:
      minimum-idle: 1
  jackson:
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
